USE [master]
GO

/****** Object:  Database [lopush]    Script Date: 04.03.2024 13:06:11 ******/
DROP DATABASE [lopush]
GO

/****** Object:  Database [lopush]    Script Date: 04.03.2024 13:06:11 ******/
CREATE DATABASE [lopush]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'lopush', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\lopush.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'lopush_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\lopush_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lopush].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lopush] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lopush] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lopush] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lopush] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lopush] SET ARITHABORT OFF 
GO

ALTER DATABASE [lopush] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lopush] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lopush] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lopush] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lopush] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lopush] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lopush] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lopush] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lopush] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lopush] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lopush] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lopush] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lopush] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lopush] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lopush] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lopush] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lopush] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lopush] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [lopush] SET  MULTI_USER 
GO

ALTER DATABASE [lopush] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lopush] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lopush] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [lopush] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [lopush] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [lopush] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [lopush] SET QUERY_STORE = OFF
GO

ALTER DATABASE [lopush] SET  READ_WRITE 
GO


